import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from '@/components/BottomNav'; 
import { ModalProvider } from '@/components/ModalContext';
import ModalWrapper from '@/components/ModalWrapper';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="he" 
      dir="rtl" 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </head>

      <body className="min-h-full flex flex-col">
        <ModalProvider>
          
          <main className="flex-grow">
            {children}
          </main>

          <BottomNav />
          <ModalWrapper />
          
        </ModalProvider>
      </body>
    </html>
  );
}