import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from '@/components/ModalContext';
import ModalWrapper from '@/components/ModalWrapper';
import ConditionalBottomNav from '@/components/ConditionalBottomNav'; // ייבוא הקומפוננטה החדשה

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // app/layout.tsx
  return (
    <html lang="he" dir="rtl" className="h-full">
      <body className="h-full flex flex-col relative">
        <ModalProvider>
          {/* הוספנו h-full ו-overflow-y-auto כדי שהגלילה תהיה פנימית */}
          <main className="flex-grow overflow-y-auto">
            {children}
            
            {/* ה-SPACER: האלמנט הזה "יחזיק" את המקום של ה-Navbar */}
            {/* גובה הבר שלך הוא 70px + 20px מרווח = 90px */}
            <div className="h-[100px] w-full flex-shrink-0"></div>
          </main>

          <ConditionalBottomNav />
          <ModalWrapper /> 
        </ModalProvider>
      </body>
    </html>
  );
}